version: '3.8'

services:
  tomcat:
    image: tomcat:jre21-temurin-jammy
    ports:
      - "8280:8080"  # Map port 8080 on the container to port 8280 on the host
    volumes:
      - ./target/lectures-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/lectures.war # Mount the WAR file
    restart: always